<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Electronics Category
            [
                'name' => 'Samsung Galaxy S24',
                'description' => 'Latest Samsung flagship with AI features, 256GB storage',
                'category' => 'Electronics',
                'selling_price' => 45999.00,
                'commission_rate' => 8.00,
                'total_item_available' => 25,
                'merchant_name' => 'TechHub Kenya',
                'merchant_phone' => '0712345678',
                'merchant_email' => 'sales@techhub.co.ke',
                'within_region_delivery_fee' => 200.00,
                'outside_region_delivery_fee' => 500.00,
                'image_url' => 'https://example.com/images/samsung-s24.jpg',
                'sku' => 'ELEC-SAM-S24-256',
                'punguzo_product_id' => 'PZ-ELEC-001',
            ],
            [
                'name' => 'iPhone 15 Pro Max',
                'description' => 'Apple iPhone 15 Pro Max, 512GB, Titanium finish',
                'category' => 'Electronics',
                'selling_price' => 89999.00,
                'commission_rate' => 10.00,
                'total_item_available' => 15,
                'merchant_name' => 'TechHub Kenya',
                'merchant_phone' => '0712345678',
                'merchant_email' => 'sales@techhub.co.ke',
                'within_region_delivery_fee' => 200.00,
                'outside_region_delivery_fee' => 500.00,
                'image_url' => 'https://example.com/images/iphone15.jpg',
                'sku' => 'ELEC-APP-I15PM-512',
                'punguzo_product_id' => 'PZ-ELEC-002',
            ],
            [
                'name' => 'HP Pavilion Laptop',
                'description' => 'HP Pavilion 15, Intel Core i7, 16GB RAM, 512GB SSD',
                'category' => 'Electronics',
                'selling_price' => 65000.00,
                'commission_rate' => 9.00,
                'total_item_available' => 20,
                'merchant_name' => 'Computers Direct',
                'merchant_phone' => '0723456789',
                'merchant_email' => 'info@computersdirect.co.ke',
                'within_region_delivery_fee' => 300.00,
                'outside_region_delivery_fee' => 700.00,
                'image_url' => 'https://example.com/images/hp-pavilion.jpg',
                'sku' => 'ELEC-HP-PAV15-I7',
                'punguzo_product_id' => 'PZ-ELEC-003',
            ],

            // Fashion Category
            [
                'name' => 'Men\'s Formal Suit',
                'description' => 'Premium 3-piece business suit, Navy Blue, Various sizes',
                'category' => 'Fashion',
                'selling_price' => 12500.00,
                'commission_rate' => 7.00,
                'total_item_available' => 40,
                'merchant_name' => 'Fashion Forward',
                'merchant_phone' => '0734567890',
                'merchant_email' => 'orders@fashionforward.co.ke',
                'within_region_delivery_fee' => 150.00,
                'outside_region_delivery_fee' => 400.00,
                'image_url' => 'https://example.com/images/mens-suit.jpg',
                'sku' => 'FASH-MEN-SUIT-NB',
                'punguzo_product_id' => 'PZ-FASH-001',
            ],
            [
                'name' => 'Ladies Handbag',
                'description' => 'Genuine leather handbag, Designer collection',
                'category' => 'Fashion',
                'selling_price' => 4500.00,
                'commission_rate' => 6.00,
                'total_item_available' => 60,
                'merchant_name' => 'Fashion Forward',
                'merchant_phone' => '0734567890',
                'merchant_email' => 'orders@fashionforward.co.ke',
                'within_region_delivery_fee' => 100.00,
                'outside_region_delivery_fee' => 300.00,
                'image_url' => 'https://example.com/images/handbag.jpg',
                'sku' => 'FASH-LAD-BAG-001',
                'punguzo_product_id' => 'PZ-FASH-002',
            ],

            // Home & Living
            [
                'name' => '6-Seater Dining Set',
                'description' => 'Mahogany dining table with 6 cushioned chairs',
                'category' => 'Home & Living',
                'selling_price' => 85000.00,
                'commission_rate' => 12.00,
                'total_item_available' => 8,
                'merchant_name' => 'Home Comfort Furniture',
                'merchant_phone' => '0745678901',
                'merchant_email' => 'sales@homecomfort.co.ke',
                'within_region_delivery_fee' => 1500.00,
                'outside_region_delivery_fee' => 3500.00,
                'image_url' => 'https://example.com/images/dining-set.jpg',
                'sku' => 'HOME-FURN-DIN6',
                'punguzo_product_id' => 'PZ-HOME-001',
            ],
            [
                'name' => '32 inch Smart TV',
                'description' => 'LG Smart TV, 32 inches, Full HD, Netflix enabled',
                'category' => 'Home & Living',
                'selling_price' => 22000.00,
                'commission_rate' => 8.00,
                'total_item_available' => 30,
                'merchant_name' => 'Electronics Plaza',
                'merchant_phone' => '0756789012',
                'merchant_email' => 'info@electronicplaza.co.ke',
                'within_region_delivery_fee' => 500.00,
                'outside_region_delivery_fee' => 1000.00,
                'image_url' => 'https://example.com/images/lg-tv.jpg',
                'sku' => 'HOME-TV-LG32',
                'punguzo_product_id' => 'PZ-HOME-002',
            ],

            // Beauty & Health
            [
                'name' => 'Skin Care Set',
                'description' => 'Complete facial care set with cleanser, toner, moisturizer',
                'category' => 'Beauty & Health',
                'selling_price' => 3500.00,
                'commission_rate' => 5.00,
                'total_item_available' => 100,
                'merchant_name' => 'Beauty Essentials',
                'merchant_phone' => '0767890123',
                'merchant_email' => 'orders@beautyessentials.co.ke',
                'within_region_delivery_fee' => 100.00,
                'outside_region_delivery_fee' => 250.00,
                'image_url' => 'https://example.com/images/skincare-set.jpg',
                'sku' => 'BEAUTY-SKIN-SET01',
                'punguzo_product_id' => 'PZ-BEAUTY-001',
            ],

            // Sports & Outdoors
            [
                'name' => 'Mountain Bike',
                'description' => '21-speed mountain bike, aluminum frame, 26 inch wheels',
                'category' => 'Sports & Outdoors',
                'selling_price' => 28000.00,
                'commission_rate' => 10.00,
                'total_item_available' => 12,
                'merchant_name' => 'Sports Universe',
                'merchant_phone' => '0778901234',
                'merchant_email' => 'sales@sportsuniverse.co.ke',
                'within_region_delivery_fee' => 800.00,
                'outside_region_delivery_fee' => 1800.00,
                'image_url' => 'https://example.com/images/mountain-bike.jpg',
                'sku' => 'SPORT-BIKE-MTN26',
                'punguzo_product_id' => 'PZ-SPORT-001',
            ],
            [
                'name' => 'Yoga Mat Premium',
                'description' => 'Non-slip yoga mat, 6mm thickness, with carrying strap',
                'category' => 'Sports & Outdoors',
                'selling_price' => 2500.00,
                'commission_rate' => 4.00,
                'total_item_available' => 50,
                'merchant_name' => 'Sports Universe',
                'merchant_phone' => '0778901234',
                'merchant_email' => 'sales@sportsuniverse.co.ke',
                'within_region_delivery_fee' => 150.00,
                'outside_region_delivery_fee' => 350.00,
                'image_url' => 'https://example.com/images/yoga-mat.jpg',
                'sku' => 'SPORT-YOGA-MAT6',
                'punguzo_product_id' => 'PZ-SPORT-002',
            ],

            // Groceries
            [
                'name' => 'Rice - 25kg Bag',
                'description' => 'Premium Pishori rice, 25kg family pack',
                'category' => 'Groceries',
                'selling_price' => 4200.00,
                'commission_rate' => 3.00,
                'total_item_available' => 200,
                'merchant_name' => 'Fresh Foods Market',
                'merchant_phone' => '0789012345',
                'merchant_email' => 'orders@freshfoods.co.ke',
                'within_region_delivery_fee' => 200.00,
                'outside_region_delivery_fee' => 500.00,
                'image_url' => 'https://example.com/images/rice-bag.jpg',
                'sku' => 'GROC-RICE-25KG',
                'punguzo_product_id' => 'PZ-GROC-001',
            ],
            [
                'name' => 'Cooking Oil - 20L',
                'description' => 'Fresh Fri cooking oil, 20 liter jerrycan',
                'category' => 'Groceries',
                'selling_price' => 3800.00,
                'commission_rate' => 3.00,
                'total_item_available' => 150,
                'merchant_name' => 'Fresh Foods Market',
                'merchant_phone' => '0789012345',
                'merchant_email' => 'orders@freshfoods.co.ke',
                'within_region_delivery_fee' => 250.00,
                'outside_region_delivery_fee' => 600.00,
                'image_url' => 'https://example.com/images/cooking-oil.jpg',
                'sku' => 'GROC-OIL-20L',
                'punguzo_product_id' => 'PZ-GROC-002',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
